spring:
  application:
    name: springbootdemo
  session:
    store-type: redis #设置session存储类型为redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器集群地址
    cluster:
      clusterNodes: 47.98.102.177:6379,47.98.102.177:6380,47.98.102.177:6381,47.98.102.177:6382,47.98.102.177:6383,47.98.102.177:6384
      maxRedirects: 6
      commandTimeout: 5000
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        testOnBorrow: true
        testWhileIdle: true
        minEvictableIdleTimeMills: 60000
        timeBetweenEvictionRunsMillis: 30000
        numTestsPerEvictionRun: -1
    # 连接超时时间（毫秒）
    timeout: 5000
logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wxc8038971c83db734
        secret: f5358c4e37dbafdae9750d82b6dccdd0
        token: fantasy
        aesKey: q1Qz7og1fQalTKBgRytqonpguKgBznfZQze9nVzGiGQ