spring:
  application:
    name: springbootdemo
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器集群地址
    cluster:
      clusterNodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
      maxRedirects: 6
      commandTimeout: 5000
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        testOnBorrow: true
        testWhileIdle: true
        minEvictableIdleTimeMills: 60000
        timeBetweenEvictionRunsMillis: 30000
        numTestsPerEvictionRun: -1
    # 连接超时时间（毫秒）
    timeout: 5000
